name: Omni Tests

on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: "Caller repository"
        required: false
        default: ""
      ref:
        type: string
        description: "Ref/sha to use for the caller repository"
        required: false
        default: ""
      test_ref:
        type: string
        description: "Ref/sha to use for omnitest"
        required: false
        default: "v1"
      test_branch:
        type: string
        description: "Branch to use for pyanodontest"
        required: false
        default: ""

env:
  GITHUB_TOKEN: ${{ secrets.TESTUSER_TOKEN }}
  EVENT_REPOSITORY: ${{ inputs.repository }}
  EVENT_REF: ${{ inputs.ref }}
  EVENT_BRANCH: ${{ inputs.test_branch }}

jobs:
  genereate_matrix:
    name: "Generate strategy matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: "Omnimods/omnitests"
          token: ${{ secrets.TESTUSER_TOKEN }}
          ref: ${{ inputs.test_ref }}
      - name: Install PyGithub
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygithub 
      - id: set-matrix
        run: |
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          echo "$(python getrefs.py)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  load_test:
    name: ${{ format('CrashTest {0}', matrix.name) }}
    needs: genereate_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.genereate_matrix.outputs.matrix) }}
    steps:
      - name: "Checkout omnitests"
        uses: actions/checkout@v4
        with:
          repository: "Omnimods/omnitests"
          token: ${{ secrets.TESTUSER_TOKEN }}
          ref: ${{ inputs.test_ref }}
      - name: "Checkout mods"
        uses: ShadowGlass0/multi-checkout@v2.0
        with:
          repositories: ${{ toJSON(matrix.mods) }}
          token: ${{ secrets.TESTUSER_TOKEN }}
      - name: "Move mods"
        run: ./movemods.sh "${{ matrix.name }}"
      - name: "TEST: Load Factorio"
        uses: ShadowGlass0/factorio-docker-for-github-actions@main
